# Generated by Django 4.2 on 2023-04-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=30, verbose_name='setting name')),
                ('setting_value', models.CharField(max_length=300, verbose_name='setting value')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True, verbose_name='tag')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=300, unique=True, verbose_name='image path')),
                ('image_name', models.CharField(max_length=30, verbose_name='image name')),
                ('tags', models.ManyToManyField(to='gallery.tag', verbose_name='tags')),
            ],
        ),
    ]
