# Generated by Django 4.2 on 2023-05-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_anything', '0002_tagcategory_alter_tag_options_alter_tag_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название'),
        ),
    ]
