# Generated by Django 4.2 on 2023-05-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'default_related_name': 'images', 'verbose_name': 'картинки', 'verbose_name_plural': 'Картинки'},
        ),
    ]
